[project]
name = "knoepfe"
version = "0.1.1"
description = "Connect and control Elgato Stream Decks"
authors = [
  { name = "Simon Hayessen", email = "simon@lnqs.io" },
  { name = "Simon Brakhane", email = "simon@brakhane.net" }
]
requires-python = ">=3.10"
readme = "README.md"
license = "GPL-3.0-or-later"
dependencies = [
  "schema>=0.7.7,<0.8",
  "appdirs>=1.4.4,<2",
  "docopt>=0.6.2,<0.7",
  "streamdeck>=0.9.5,<0.10",
  "Pillow>=10.4.0,<11",
  "aiorun>=2024.8.1,<2025",
  "pulsectl-asyncio>=1.2.1,<2",
  "pulsectl>=24.8.0,<25",
  "simpleobsws>=1.4.0",
]

[project.urls]
Homepage = "https://github.com/lnqs/knoepfe"
Repository = "https://github.com/lnqs/knoepfe"

[project.scripts]
knoepfe = "knoepfe.__main__:main"

[dependency-groups]
dev = [
  "pre-commit>=3.8.0,<4",
  "pytest>=8.3.3,<9",
  "pytest-asyncio>=0.24.0,<0.25",
  "pytest-cov>=5.0.0,<6",
  "types-appdirs>=1.4.3.5,<2",
  "types-docopt>=0.6.11.4,<0.7",
  "types-pillow>=10.2.0.20240822,<11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"
extend_skip_glob = [".venv/*"]

[tool.black]
extend-exclude = '''
(
  \.venv/               # exclude .venv directory
)
'''

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
  "StreamDeck.*",
  "pulsectl.*",
  "pulsectl_asyncio.*",
  "aiorun.*",
  "schema.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning:pulsectl_asyncio"
addopts = "--cov=knoepfe --cov-report=term-missing --asyncio-mode=auto"
