name: Run linter and tests
description: Runs the format check, linter, type check and tests

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install -y pulseaudio libhidapi-libusb0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install uv
      shell: bash
      run: python3 -m pip install uv

    - name: Setup project
      shell: bash
      run: uv sync
      env:
        UV_PROJECT_ENVIRONMENT: .venv

    - name: isort
      shell: bash
      run: uv run isort --check knoepfe/

    - name: black
      shell: bash
      run: uv run black --check knoepfe/

    - name: flake8
      shell: bash
      run: uv run flake8 knoepfe/

    - name: mypy
      shell: bash
      run: uv run mypy knoepfe/

    - name: pytest
      shell: bash
      run: uv run pytest
