name: Run linter and tests
description: Runs the format check, linter, type check and tests

runs:
  using: composite
  steps:
    - name: Disable initramfs update
      shell: bash
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

    - name: Disable man-db update
      shell: bash
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install -y pulseaudio libhidapi-libusb0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install uv
      shell: bash
      run: python3 -m pip install uv

    - name: Setup project
      shell: bash
      run: uv sync
      env:
        UV_PROJECT_ENVIRONMENT: .venv

    - name: isort
      shell: bash
      run: uv run isort --check .

    - name: black
      shell: bash
      run: uv run black --check .

    - name: flake8
      shell: bash
      run: uv run flake8 .

    - name: mypy
      shell: bash
      run: uv run mypy .

    - name: pytest
      shell: bash
      run: uv run pytest
