name: Run linter and tests
description: Runs the format check, linter, type check and tests

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install -y pulseaudio libhidapi-libusb0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install poetry
      shell: bash
      run: python3 -m pip install poetry

    - name: Setup project
      shell: bash
      run: poetry install

    - name: isort
      shell: bash
      run: poetry run isort --check .

    - name: black
      shell: bash
      run: poetry run black --check .

    - name: flake8
      shell: bash
      run: poetry run flake8 .

    - name: mypy
      shell: bash
      run: poetry run mypy .

    - name: pytest
      shell: bash
      run: poetry run pytest
