name: Run linter and tests
description: Runs the format check, linter, type check and tests

runs:
  using: composite
  steps:
    - name: Disable initramfs update
      shell: bash
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

    - name: Disable man-db update
      shell: bash
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install -y pulseaudio libhidapi-libusb0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install uv
      shell: bash
      run: python3 -m pip install uv

    - name: Setup project
      shell: bash
      run: uv sync --extra dev
      env:
        UV_PROJECT_ENVIRONMENT: .venv

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

    - name: Test core package
      shell: bash
      run: uv run pytest tests/

    - name: Test OBS plugin
      shell: bash
      run: cd plugins/obs && uv run pytest tests/

    - name: Test audio plugin
      shell: bash
      run: cd plugins/audio && uv run pytest tests/
