name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: sudo apt-get install -y pulseaudio libhidapi-libusb0
    - name: Install poetry
      run: pip install poetry
    - name: Setup project
      run: poetry install
    - name: isort
      run: poetry run isort --check .
    - name: black
      run: poetry run black --check .
    - name: flake8
      run: poetry run flake8 .
    - name: mypy
      run: poetry run mypy .
    - name: pytest
      run: poetry run pytest
